challenge/urls.py
from django.urls import path
from . import views

app_name = 'challenge'

homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.status, name='status'),
]

status/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.status, name='status'),
    path('submit/', views.submit, name="submit")
]

story/urls.py
from django.urls import path, include
from django.contrib import admin
from challenge.views import challenge

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('challenge/', challenge),
    path('status/', include('status.urls', namespace="status")),
    path('profile/', include('story8.urls', namespace="status"))
]

story8/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.profile, name='profile'),
]

challenge/models.py
from django.db import models

# Create your models here.

homepage/models.py
from django.db import models

class Status(models.Model):
    status = models.TextField('status', max_length = 300)
    time = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.status


# Create your models here.

status/models.py
from django.db import models

# Create your models here.

class StatusModel(models.Model):
    nama = models.CharField(max_length=512)
    status = models.CharField(max_length=1024)

    def __str__(self):
        return self.nama

story8/models.py
from django.db import models

# Create your models here.

homepage/forms.py
from django import forms
from .models import Status

class StatusForm(forms.ModelForm):
    status = forms.CharField(widget=forms.TextInput, required=True)
    class Meta:
        model = Status
        fields = ['status']
        widgets = {'status': forms.TextInput()}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

status/forms.py
from django import forms
from .models import StatusModel
from django.utils.translation import gettext_lazy as _

class StatusForm(forms.ModelForm):
    
    class Meta:
        model = StatusModel
        fields = '__all__'
        widgets = {
            'nama': forms.TextInput(),
            'status': forms.TextInput(),
        }
        labels = {
            'nama': _('Nama'),
            'status': _('Status'),
        }

challenge/views.py
from django.shortcuts import render
from django.shortcuts import redirect

def challenge(request):
	return render(request, 'challenge.html')

homepage/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from .models import Status
from . import forms
from .forms import StatusForm

def status(request):
	stats = Status.objects.all().values()
	if (request.method == 'POST'):
		form = StatusForm(request.POST)
		if (form.is_valid()):
			form.save()
			return redirect('/')
	else:
		form = StatusForm()
	return render(request, 'index.html', {'stats': stats, 'form':form})

status/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .models import *
from .forms import *
# Create your views here.


def status(request):
    if request.method == "POST":
        form = StatusForm(request.POST)
        if form.is_valid:
            return render(request, 'confirm.html', {'form': form})
    else:
        status = StatusModel.objects.all().values()
        form = StatusForm(auto_id=True)
        return render(request, 'status.html', {'form': form, 'status': status})


def submit(request):
    if request.method == "POST":
        form = StatusForm(request.POST)
        if form.is_valid:
            form.save()
            return redirect('status:status')

story8/views.py
from django.shortcuts import render

# Create your views here.


def profile(request):
    return render(request, 'profile.html')

challenge/templates/challenge.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link href='https://fonts.googleapis.com/css?family=Open Sans' rel='stylesheet'>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <style>
        p {
            margin: 0px;
        }
    </style>
</head>

    <body>
    <body style="background-color: #DFD1DC; font-family :Open Sans ;">
        <div class = "head-wrap" style="">
            <p style="font-size: 50px">Hello, </p>
            <p style="font-size: 30px">Inez Zahra</p>
            <p style="font-size: 30px; font-weight: bold">1806241091</p>
        </div>
    
    </body>


</html>

homepage/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link href='https://fonts.googleapis.com/css?family=Open Sans' rel='stylesheet'>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <style>
        p {
            margin: 0px;
        }
    </style>
</head>

    <body>
    <body style="background-color: #D7E2E5; font-family :Open Sans ;">
        <div class = "head-wrap" style="">
            <p style="font-size: 50px">Hello, </p>
            <p style="font-size: 30px">How are you feeling today?</p>
        </div>
        <form method="POST">
        {% csrf_token %}
        <div class="forms">
            {% for i in form %}
            {{ i }}
            {% endfor %}
        </div>
        <div class="btn">
            <input type="submit" value="submit">
        </div>
        </form>
        <div class="response">
            {% for i in stats %}
                <h1>{{ i.status }} - {{ i.time }}</h1>
              {% endfor %}
        </div>
    </body>


</html>

status/templates/confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
    <h2 class="text-center">Apakah sudah benar?</h2>
    <div class="row" style="margin-top:5rem;">
        <div class="col-md-4"></div>
        {% for i in form %}

        <div class="col-md-2">
            <p>{{i.name}}: {{i.value}}</p>
        </div>
        {% endfor %}
        <form action="{% url 'status:submit' %}" method="POST">
        {% csrf_token %}
        {% for i in form %}
            <input type="hidden" name="{{i.name}}" value="{{i.value}}">
        {% endfor %}
        <button type="submit" class="btn btn-primary" id="ya">Ya</button>
        </form>
        <a href="" class="btn btn-primary">Tidak</a>
        <div class="col-md-4"></div>
        
    </div>
    
    
    

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

status/templates/status.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link href='https://fonts.googleapis.com/css?family=Open Sans' rel='stylesheet'>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <style>
        p {
            margin: 0px;
        }
    </style>
</head>

    <body>
    <body style="background-color: #D7E2E5; font-family :Open Sans ;">
        <div class = "head-wrap" style="">
            <p style="font-size: 50px">Hello, </p>
            <p style="font-size: 30px">How are you feeling today?</p>
        </div>
        <form method="POST" >
        {% csrf_token %}
        <div class="forms">
            {% for i in form %}
            {{i.label   }}
            {{ i }}
            {% endfor %}
        </div>
        <div class="btn">
            <input type="submit" value="submit">
        </div>
        </form>
        <div class="response">
        
            {% for i in status %}
                <h1>{{ i.nama }} - {{ i.status }}</h1>
              {% endfor %}
        </div>
    </body>


</html>

story8/templates/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/stylesheet.css' %}">
</head>
<body>
  <div class="accordion-container">
  <h2>jQuery Accordion</h2>
  <div class="set">
    <a href="#" id="about">
      About 
      <i class="fa fa-chevron-up"></i>
    </a>
    <div class="content">
      <p>My name is Inez Zahra Nabila, an undergraduate student that currently pursuing Computer Science at Faculty of Computer Science University of Indonesia .</p>
    </div>
  </div>
  <div class="set">
    <a href="#" id="activity">
      Current Activities 
      <i class="fa fa-chevron-up"></i>
    </a>
    <div class="content">
      <p>Pursuing Computer Science.</p>
    </div>
    <div class="content">
      <p>HEAD OF PUBLIC RELATION.</p>
      <p>Dewan Perwakilan Mahasiswa Fakultas Ilmu
Komputer Universitas Indonesia | 2019-present.</p>
    </div>
  </div>
  <div class="set">
    <a href="#" id="experience">
      Organizational/Committee Experiences 
      <i class="fa fa-chevron-up"></i>
    </a>
    <div class="content">
      <p>PROJECT OFFICER / CHIEF OFFICER.</p>
      <p>Wisuda Fakultas Ilmu Komputer Semester Genap |
2019.</p>
    </div>
    
  </div>
  <div class="set">
    <a href="#" id="achievement">
      Achievements 
      <i class="fa fa-chevron-up"></i>
    </a>
    <div class="content">
      <p>ENGLISH PROFICIENCY TEST, College Board Scholastic Assessment Test (SAT) </p>
      <p>Gaining Score 1340 of 1600 </p>
    </div>
  </div>
</div>
    
    
   <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<script src="{% static 'js/script.js' %}"></script>
</body>
</html>